<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('books')->insert([
            // Fiksi
            [
                'isbn' => '9786020321231',
                'judul' => 'Laskar Pelangi',
                'penerbit' => 'Bentang Pustaka',
                'penulis' => 'Andrea Hirata',
                'deskripsi' => 'Kisah inspiratif anak-anak miskin di Belitung.',
                'diterbitkan' => '2005-09-01',
                'cover' => 'cover/laskar-pelangi.jpg',
                'kategori_id' => 1,
                'stok' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786021234567',
                'judul' => 'Bumi',
                'penerbit' => 'Gramedia Pustaka Utama',
                'penulis' => 'Tere Liye',
                'deskripsi' => 'Petualangan dunia paralel remaja bernama Raib.',
                'diterbitkan' => '2014-01-01',
                'cover' => 'cover/bumi.jpg',
                'kategori_id' => 1,
                'stok' => 7,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786021234568',
                'judul' => 'Hujan',
                'penerbit' => 'Gramedia Pustaka Utama',
                'penulis' => 'Tere Liye',
                'deskripsi' => 'Kisah masa depan dan cinta penuh haru.',
                'diterbitkan' => '2016-01-01',
                'cover' => 'cover/hujan.jpg',
                'kategori_id' => 1,
                'stok' => 5,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Non Fiksi
            [
                'isbn' => '9786024251230',
                'judul' => 'Sebuah Seni untuk Bersikap Bodo Amat',
                'penerbit' => 'Gramedia',
                'penulis' => 'Mark Manson',
                'deskripsi' => 'Panduan hidup dengan lebih santai dan realistis.',
                'diterbitkan' => '2016-10-01',
                'cover' => 'cover/seni-bodo-amat.jpg',
                'kategori_id' => 2,
                'stok' => 8,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523345',
                'judul' => 'Atomic Habits',
                'penerbit' => 'Random House',
                'penulis' => 'James Clear',
                'deskripsi' => 'Cara membangun kebiasaan kecil untuk perubahan besar.',
                'diterbitkan' => '2018-10-16',
                'cover' => 'cover/atomic-habits.jpg',
                'kategori_id' => 2,
                'stok' => 6,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523346',
                'judul' => 'Berani Tidak Disukai',
                'penerbit' => 'Gramedia',
                'penulis' => 'Ichiro Kishimi & Fumitake Koga',
                'deskripsi' => 'Filosofi hidup berdasarkan ajaran Alfred Adler.',
                'diterbitkan' => '2019-01-01',
                'cover' => 'cover/berani-tidak-disukai.jpg',
                'kategori_id' => 2,
                'stok' => 4,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Komik
            [
                'isbn' => '9784088700100',
                'judul' => 'One Piece',
                'penerbit' => 'Shueisha',
                'penulis' => 'Eiichiro Oda',
                'deskripsi' => 'Petualangan bajak laut mencari harta karun One Piece.',
                'diterbitkan' => '1997-07-22',
                'cover' => 'cover/one-piece.jpg',
                'kategori_id' => 3,
                'stok' => 15,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9784088521366',
                'judul' => 'Doraemon',
                'penerbit' => 'Shogakukan',
                'penulis' => 'Fujiko F. Fujio',
                'deskripsi' => 'Robot kucing dari masa depan yang membantu Nobita.',
                'diterbitkan' => '1969-12-01',
                'cover' => 'cover/doraemon.jpg',
                'kategori_id' => 3,
                'stok' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9784088725092',
                'judul' => 'Naruto',
                'penerbit' => 'Shueisha',
                'penulis' => 'Masashi Kishimoto',
                'deskripsi' => 'Perjalanan ninja muda bernama Naruto Uzumaki.',
                'diterbitkan' => '1999-09-21',
                'cover' => 'cover/naruto.jpg',
                'kategori_id' => 3,
                'stok' => 12,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],

                        // Ensiklopedia
            [
                'isbn' => '9786024523347',
                'judul' => 'Ensiklopedia Sains dan Teknologi Anak',
                'penerbit' => 'Bhuana Ilmu Populer',
                'penulis' => 'Tim BIP',
                'deskripsi' => 'Pengetahuan sains dan teknologi untuk anak-anak.',
                'diterbitkan' => '2020-03-01',
                'cover' => 'cover/ensiklopedia-anak.jpg',
                'kategori_id' => 4,
                'stok' => 6,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'isbn' => '9786024523348',
                'judul' => 'Ensiklopedia Dunia Hewan',
                'penerbit' => 'DK Publishing',
                'penulis' => 'DK Team',
                'deskripsi' => 'Informasi lengkap tentang dunia hewan dari seluruh dunia.',
                'diterbitkan' => '2017-06-15',
                'cover' => 'cover/ensiklopedia-hewan.jpg',
                'kategori_id' => 4,
                'stok' => 5,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523349',
                'judul' => 'Ensiklopedia Islam untuk Pelajar',
                'penerbit' => 'Lentera Hati',
                'penulis' => 'Tim Lentera',
                'deskripsi' => 'Pengetahuan dasar tentang Islam bagi pelajar.',
                'diterbitkan' => '2018-09-10',
                'cover' => 'cover/ensiklopedia-islam.jpg',
                'kategori_id' => 4,
                'stok' => 4,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Biografi
            [
                'isbn' => '9786024523350',
                'judul' => 'Habibie & Ainun',
                'penerbit' => 'THI',
                'penulis' => 'B.J. Habibie',
                'deskripsi' => 'Kisah cinta dan perjuangan Presiden RI ke-3 dan istrinya.',
                'diterbitkan' => '2010-01-01',
                'cover' => 'cover/habibie-ainun.jpg',
                'kategori_id' => 5,
                'stok' => 6,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523351',
                'judul' => 'Steve Jobs',
                'penerbit' => 'Simon & Schuster',
                'penulis' => 'Walter Isaacson',
                'deskripsi' => 'Biografi resmi pendiri Apple Inc.',
                'diterbitkan' => '2011-10-24',
                'cover' => 'cover/steve-jobs.jpg',
                'kategori_id' => 5,
                'stok' => 5,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523352',
                'judul' => 'Soekarno: Penyambung Lidah Rakyat',
                'penerbit' => 'Gunung Agung',
                'penulis' => 'Cindy Adams',
                'deskripsi' => 'Biografi Presiden pertama Indonesia.',
                'diterbitkan' => '1965-01-01',
                'cover' => 'cover/soekarno.jpg',
                'kategori_id' => 5,
                'stok' => 5,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sejarah
            [
                'isbn' => '9786024523353',
                'judul' => 'Sejarah Dunia yang Disembunyikan',
                'penerbit' => 'Serambi',
                'penulis' => 'Jonathan Black',
                'deskripsi' => 'Menelusuri sejarah rahasia dari zaman kuno hingga modern.',
                'diterbitkan' => '2012-03-10',
                'cover' => 'cover/sejarah-dunia.jpg',
                'kategori_id' => 6,
                'stok' => 4,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523354',
                'judul' => 'Detik-Detik Proklamasi',
                'penerbit' => 'Yayasan API',
                'penulis' => 'Sukarni',
                'deskripsi' => 'Dokumentasi sejarah proklamasi kemerdekaan Indonesia.',
                'diterbitkan' => '1980-08-17',
                'cover' => 'cover/detik-proklamasi.jpg',
                'kategori_id' => 6,
                'stok' => 3,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523355',
                'judul' => 'Napoleon: A Life',
                'penerbit' => 'Penguin Books',
                'penulis' => 'Andrew Roberts',
                'deskripsi' => 'Biografi mendalam tokoh militer Napoleon Bonaparte.',
                'diterbitkan' => '2014-11-04',
                'cover' => 'cover/napoleon.jpg',
                'kategori_id' => 6,
                'stok' => 4,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sains
            [
                'isbn' => '9786024523356',
                'judul' => 'Brief Answers to the Big Questions',
                'penerbit' => 'Bantam Books',
                'penulis' => 'Stephen Hawking',
                'deskripsi' => 'Jawaban singkat untuk pertanyaan terbesar dalam sains.',
                'diterbitkan' => '2018-10-16',
                'cover' => 'cover/brief-answers.jpg',
                'kategori_id' => 7,
                'stok' => 5,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523357',
                'judul' => 'Sapiens: A Brief History of Humankind',
                'penerbit' => 'Harvill Secker',
                'penulis' => 'Yuval Noah Harari',
                'deskripsi' => 'Sejarah singkat evolusi manusia modern.',
                'diterbitkan' => '2011-01-01',
                'cover' => 'cover/sapiens.jpg',
                'kategori_id' => 7,
                'stok' => 5,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523358',
                'judul' => 'The Selfish Gene',
                'penerbit' => 'Oxford University Press',
                'penulis' => 'Richard Dawkins',
                'deskripsi' => 'Pandangan evolusi dari sudut pandang gen.',
                'diterbitkan' => '1976-03-15',
                'cover' => 'cover/selfish-gene.jpg',
                'kategori_id' => 7,
                'stok' => 4,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Agama
            [
                'isbn' => '9786024523359',
                'judul' => 'Fiqh Sunnah',
                'penerbit' => 'Darul Fikr',
                'penulis' => 'Sayyid Sabiq',
                'deskripsi' => 'Pembahasan lengkap fikih berdasarkan Al-Qur’an dan Sunnah.',
                'diterbitkan' => '1954-01-01',
                'cover' => 'cover/fiqh-sunnah.jpg',
                'kategori_id' => 8,
                'stok' => 6,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523360',
                'judul' => 'Tafsir Al-Mishbah',
                'penerbit' => 'Lentera Hati',
                'penulis' => 'Quraish Shihab',
                'deskripsi' => 'Tafsir Al-Qur’an tematik dan kontekstual.',
                'diterbitkan' => '2002-01-01',
                'cover' => 'cover/tafsir-mishbah.jpg',
                'kategori_id' => 8,
                'stok' => 4,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523361',
                'judul' => 'La Tahzan (Jangan Bersedih)',
                'penerbit' => 'Qisthi Press',
                'penulis' => '‘Aidh al-Qarni',
                'deskripsi' => 'Motivasi islami agar tidak bersedih dalam menghadapi hidup.',
                'diterbitkan' => '2003-01-01',
                'cover' => 'cover/la-tahzan.jpg',
                'kategori_id' => 8,
                'stok' => 7,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Novel
            [
                'isbn' => '9786024523362',
                'judul' => 'Ayat-Ayat Cinta',
                'penerbit' => 'Republika',
                'penulis' => 'Habiburrahman El Shirazy',
                'deskripsi' => 'Kisah cinta dan religi seorang mahasiswa Indonesia di Mesir.',
                'diterbitkan' => '2004-01-01',
                'cover' => 'cover/ayat-ayat-cinta.jpg',
                'kategori_id' => 9,
                'stok' => 5,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523363',
                'judul' => 'Perahu Kertas',
                'penerbit' => 'Bentang Pustaka',
                'penulis' => 'Dee Lestari',
                'deskripsi' => 'Kisah cinta dua anak muda yang penuh konflik dan seni.',
                'diterbitkan' => '2009-10-01',
                'cover' => 'cover/perahu-kertas.jpg',
                'kategori_id' => 9,
                'stok' => 6,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523364',
                'judul' => 'Dilan: Dia adalah Dilanku Tahun 1990',
                'penerbit' => 'Pastel Books',
                'penulis' => 'Pidi Baiq',
                'deskripsi' => 'Cerita cinta remaja SMA tahun 90-an di Bandung.',
                'diterbitkan' => '2014-01-01',
                'cover' => 'cover/dilan.jpg',
                'kategori_id' => 9,
                'stok' => 8,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Puisi
            [
                'isbn' => '9786024523365',
                'judul' => 'Hujan Bulan Juni',
                'penerbit' => 'Gramedia',
                'penulis' => 'Sapardi Djoko Damono',
                'deskripsi' => 'Kumpulan puisi romantis dan kontemplatif.',
                'diterbitkan' => '1994-01-01',
                'cover' => 'cover/hujan-bulan-juni.jpg',
                'kategori_id' => 10,
                'stok' => 4,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523366',
                'judul' => 'Aku',
                'penerbit' => 'Balai Pustaka',
                'penulis' => 'Chairil Anwar',
                'deskripsi' => 'Puisi legendaris yang menjadi simbol perlawanan.',
                'diterbitkan' => '1943-01-01',
                'cover' => 'cover/aku.jpg',
                'kategori_id' => 10,
                'stok' => 3,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '9786024523367',
                'judul' => 'Derai-derai Cemara',
                'penerbit' => 'Balai Pustaka',
                'penulis' => 'Chairil Anwar',
                'deskripsi' => 'Puisi tentang kesendirian dan kematian.',
                'diterbitkan' => '1949-01-01',
                'cover' => 'cover/derai-cemara.jpg',
                'kategori_id' => 10,
                'stok' => 2,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],


        ]);
    }
}
